#Application Configuration
server:
  port: 5008
  error:
    include-message: always
    include-binding-errors: always

spring:
  codec:
    max-in-memory-size: 16MB
  mvc:
    async:
      request-timeout: 120000
  webflux:
    session:
      timeout: 120s
    netty:
      idle-timeout: 120s
  r2dbc:
    url: r2dbc:mariadb://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}?autoReconnect=true
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    pool:
      max-size: 50
      max-acquire-time: 30000
      max-idle-time: 60000
  data:
    r2dbc:
      repositories:
        enabled: true
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}?autoReconnect=true
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MariaDBDialect

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    org.springframework.web: ERROR
    org.springframework.boot: ERROR
    your.package.name: ERROR

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@${EUREKA_HOSTNAME}:${EUREKA_PORT}/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
api:
  backoffice-firebase:
    url: lb://backoffice-firebase/backoffice/api/v1/messaging
