#Application Configuration
server:
  port: 5009
  error:
    include-message: always
    include-binding-errors: always

spring:        
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}?autoReconnect=true
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    # hikari:
    #   maximum-pool-size: 5
    #   minimum-idle: 4
    #   idle-timeout: 60000  # 1 minuto
    #   max-lifetime: 900000  # 15 minutos
    #   connection-timeout: 30000  # 30 segundos

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MariaDBDialect

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@${EUREKA_HOSTNAME}:${EUREKA_PORT}/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
api:
  backoffice-firebase:
    url: lb://backoffice-firebase/backoffice/api/v1/messaging

url:
  #messaging: http://backoffice-firebase/backoffice/api/v1/messaging
  messaging: ${FIREBASE_URL}
